### ISSUE TITLE
Autoplay stops after clicking the pager

### ISSUE THREAD

**Issue by madelyncruz** [getgrav/grav-plugin-lightslider#13] opened 2016-01-19 02:48 UTC
Clicking the next/prev pager works, but autoplay stops working. I've checked the plugin configurations, but seems like there's no configuration there like "enable/disable pause on controls". Is there any other way to continue the slider upon clicking the pager?

Below is my current configuration:

$(document).ready(function() {
    $("#Slider-ID").lightSlider({
        item: 1,
        slideMove: 1,
        slideMargin: 0,
        mode: 'fade',
        cssEasing: 'ease',
        easing: '',
        speed: 1500,
        auto: true,
        loop: true,
        pause: 6000,
        controls: true,
        keyPress: true,
        adaptiveHeight: true,
        vertical: false,
        verticalHeight: 500,
        pager: false,
        gallery: false,
        galleryMargin: 15,
        thumbMargin: 5,
        enableTouch: true,
        enableDrag: false,
    });
  });

**Comment by madelyncruz** [comment] 2016-01-19 06:08
I've applied the js code provided in here http://sachinchoolur.github.io/lightslider/src/js/lightslider.js where the sample slider slides continuously after clicking the controls. I think this should be fixed in the next update.

**Comment by flaviocopes** [comment] 2016-01-19 08:38
This is a LightSlider upstream issue https://github.com/sachinchoolur/lightslider/issues/52. The linked issue says "will fix" but I didn't see it solved in the commits (I might be wrong). Unfortunately the JS lib used by this plugin comes with that problem, we cannot solve it without forking that lib.

**Comment by flaviocopes** [comment] 2016-01-19 08:43
Looks like we need to update the Lightslider version installed

**Comment by flaviocopes** [comment] 2016-01-19 09:15
Committed the update. Please test the new changes to confirm the issue is solved. It's not yet a release so you need to download the plugin code from here and put it under /user/plugins/lightslider/

**Comment by madelyncruz** [comment] 2016-01-19 11:52
Hi flaviocopes,

I have tested the new update and it's working properly. The new configuration is a big help. Thank you.

**Closed** 2016-01-19 12:28 UTC
Labels: bug
